version: '3.8'

services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./mongodb_data:/data/db/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=workout_keeper_service

volumes:
  mongodb_data:
    driver: local